language: c
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.7
      env:
         - MATRIX_EVAL="CC=gcc-4.7 && CXX=g++-4.7"


      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=gcc-4.7 && CXX=g++-4.7"
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test CTEST_OUTPUT_ON_FAILURE=TRUE
    - cd ..
    - mvn install
    

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - gcc-4.7
        
