language: c
matrix:
    include:
        - os: linux
          dist: trusty
        - os: osx
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test CTEST_OUTPUT_ON_FAILURE=TRUE
    - cd ..
    - mvn install
