language: c
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.7
      env:
         - MATRIX_EVAL="CC=gcc-4.7 && CXX=g++-4.7"


      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=gcc-4.7 && CXX=g++-4.7"

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="gcc-4.7";
      export CXX="g++-4.7";
      export LINK="gcc-4.7";
      export LINKXX="g++-4.7";
    fi
  - nvm --version
  - node --version
  - npm --version
  - gcc --version
  - g++ --version
        
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test CTEST_OUTPUT_ON_FAILURE=TRUE
    - cd ..
    - mvn install
    

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - gcc-4.7
        
